# Generated by Django 5.0.4 on 2024-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlName', models.CharField(max_length=255, null=True)),
                ('fullUrl', models.TextField()),
                ('shortenedUrl', models.TextField()),
            ],
        ),
    ]
