# Generated by Django 5.0.4 on 2024-04-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UrlShortenerApp', '0002_delete_urlqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrCodeName', models.CharField(max_length=255)),
                ('qrCode', models.TextField(blank=True, null=True)),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UrlShortenerApp.url')),
            ],
        ),
    ]
